"""add doctor_window_confirmations

Revision ID: 16848072bba0
Revises: 868664ebe4f0
Create Date: 2026-06-08 18:41:34.943598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16848072bba0'
down_revision = '868664ebe4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_window_confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['filling_windows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'window_id', name='uq_doctor_window_confirmation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_window_confirmations')
    # ### end Alembic commands ###
