"""add holidays table

Revision ID: 1a6a8602ae90
Revises: 16848072bba0
Create Date: 2026-06-10 21:31:24.868393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6a8602ae90'
down_revision = '16848072bba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['window_id'], ['filling_windows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('window_id', 'date', 'name', name='uq_holiday_window_date_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holidays')
    # ### end Alembic commands ###
