"""add location_scale_requirements, drop locations.address

Revision ID: 385908409214
Revises: e356afc0a0b4
Create Date: 2026-06-12 13:17:01.720550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385908409214'
down_revision = 'e356afc0a0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_scale_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=100), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'scale_type', name='uq_location_scale_requirement')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###

    # Dados: no CIAS, apenas P1 é obrigatório para cobertura (P2/P3 opcionais)
    op.execute("""
        INSERT INTO location_scale_requirements (location_id, scale_type, required)
        SELECT id, st, false
        FROM locations, (VALUES ('P2'), ('P3')) AS opt(st)
        WHERE name = 'CIAS'
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('location_scale_requirements')
    # ### end Alembic commands ###
