"""add coverage acceptances table

Revision ID: 4dfa592a68f0
Revises: 9457b1122c91
Create Date: 2026-06-11 21:08:34.928538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfa592a68f0'
down_revision = '9457b1122c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('scale_type', sa.String(length=100), nullable=True),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['filling_windows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('window_id', 'date', 'location_id', 'scale_type', name='uq_coverage_acceptance_window_date_location_scale')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coverage_acceptances')
    # ### end Alembic commands ###
