"""add week_number to doctor_routines

Revision ID: 6bad082406a6
Revises: 65bf51a1fe51
Create Date: 2026-06-21 23:30:34.083164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bad082406a6'
down_revision = '65bf51a1fe51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_routines', schema=None) as batch_op:
        batch_op.drop_column('week_number')

    # ### end Alembic commands ###
