"""add coverage exceptions table

Revision ID: 9457b1122c91
Revises: 1a6a8602ae90
Create Date: 2026-06-11 18:28:23.222998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9457b1122c91'
down_revision = '1a6a8602ae90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['filling_windows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('window_id', 'date', 'location_id', name='uq_coverage_exception_window_date_location')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coverage_exceptions')
    # ### end Alembic commands ###
